version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb+srv://chatbos:chatbos123@cluster0.xpibyq2.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DB=chatbos
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - mongo
    networks:
      - mentalbloom-network

  sentiment-analysis:
    build:
      context: ./ml-services/sentiment-analysis
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - sentiment-logs:/app/logs
      - sentiment-models:/app/models
    depends_on:
      - redis
    networks:
      - mentalbloom-network

  intent-recognition:
    build:
      context: ./ml-services/intent-recognition
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - intent-logs:/app/logs
      - intent-models:/app/models
    depends_on:
      - redis
    networks:
      - mentalbloom-network

  rag-service:
    build:
      context: ./rag-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PORT=8002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SENTIMENT_SERVICE_URL=http://sentiment-analysis:8000
      - INTENT_SERVICE_URL=http://intent-recognition:8001
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX_NAME=mentallbloom  # Make sure this matches your Pinecone index name
      - PINECONE_NAMESPACE=mental-health-resources

    volumes:
      - rag-logs:/app/logs
      - rag-models:/app/models
    depends_on:
      - redis
      - sentiment-analysis
      - intent-recognition

    networks:
      - mentalbloom-network



  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mentalbloom-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mentalbloom-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:8080
      - SENTIMENT_SERVICE_URL=http://sentiment-analysis:8000
      - INTENT_SERVICE_URL=http://intent-recognition:8001
      - RAG_SERVICE_URL=http://rag-service:8002
      - JWT_SECRET=your-secret-key-change-in-production
    volumes:
      - api-gateway-logs:/app/logs
    depends_on:
      - auth-service
      - sentiment-analysis
      - intent-recognition
      - rag-service
    networks:
      - mentalbloom-network

  frontend:
    build:
      context: ./frontend/mentalbloom-client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api-gateway:3000/api
    depends_on:
      - api-gateway
    networks:
      - mentalbloom-network

networks:
  mentalbloom-network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
  sentiment-logs:
  sentiment-models:
  intent-logs:
  intent-models:
  rag-logs:
  rag-models:
  api-gateway-logs:

